apiVersion: v1
kind: List
items:
  - kind: Secret
    apiVersion: v1
    data:
      password: WTRueXM3ZjEx
      username: cHJvZHVzZXI=
    metadata:
      name: prod-db-secret
      namespace: example
  - kind: Secret
    apiVersion: v1
    data:
      password: aWx1dnRlc3Rz
      username: dGVzdHVzZXI=
    
    metadata:
      name: test-db-secret
      namespace: example