apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
  namespace: example
  labels:
      name: secret-test
spec:
  containers:
    - name: ssh-test-container
      image: busybox
      args:
      - sleep
      - "1000"
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: ssh-key-secret