apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: fedora
spec:
  running: true
  template:
    spec:
      domain:
        resources:
          requests:
            memory: 1024M
          limits:
            memory: 2048M
        devices:      
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: emptydisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
      volumes:
      - name: containerdisk
        containerDisk:
          image: kubevirt/fedora-cloud-container-disk-demo:latest
      - name: emptydisk
        emptyDisk:
          capacity: 2Gi
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: a
            chpasswd: { expire: False }
