apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kh-editor
  namespace: tmax
subjects:
- kind: ServiceAccount
  name: kh
  namespace: tmax
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dave-editor
  namespace: tmax
subjects:
- kind: ServiceAccount
  name: dave
  namespace: tmax
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io