apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tmax:role:kh
  namespace: tmax
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tmax:role:dave
  namespace: tmax
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - apple